[versions]
# Minecraft
minecraft1201 = "1.20.1"
minecraft1211 = "1.21.1"
fabricx = "0.16.9"
forge1201 = "47.3.0"
neoforge1211 = "21.1.216"
# Common
cloche = "0.16.27"
kotlin = "2.2.10"
parchment1201 = "2023.09.03"
parchment1211 = "2024.11.17"
mixin = "0.8.3"
mixinextras = "0.4.1"
kotlinx-serialization = "1.8.0"
kotlinx-coroutines = "1.10.1"
bytecodecs = "1.0.2"
kritter1201 = "0.1.12+1.20.1"
kritter1211 = "0.1.12+1.21.1"
# Fabric
fapi1201 = "0.92.2"
fapi1211 = "0.116.7"
fabrickotlin = "1.13.6+kotlin.2.2.20"
fabric-iris1201 = "1.7.6+1.20.1"
fabric-iris1211 = "1.8.8+1.21.1-fabric"
# Forge
kff1201 = "4.12.0"
kff1211 = "5.10.0"
forge-iris1201 = "1.20.1-1.8.0"
forge-iris1211 = "1.8.12+1.21.1-neoforge"

[libraries]
# Common
javax-annotations = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixinextras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
# Intentionally using latest kt metadata version for more compatibility
kotlin-metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version = "2.1.20" }
bytecodecs = { module = "com.teamresourceful:bytecodecs", version.ref = "bytecodecs" }
kritter1201 = { module = "uwu.serenity.kritter:kritter-common", version.ref = "kritter1201" }
kritter1211 = { module = "uwu.serenity.kritter:kritter-common", version.ref = "kritter1211" }

# Fabric
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabrickotlin" }
fabric-kritter1201 = { module = "uwu.serenity.kritter:kritter-fabric", version.ref = "kritter1201" }
fabric-kritter1211 = { module = "uwu.serenity.kritter:kritter-fabric", version.ref = "kritter1211" }
fabric-iris1201 = { module = "maven.modrinth:iris", version.ref = "fabric-iris1201" }
fabric-iris1211 = { module = "maven.modrinth:iris", version.ref = "fabric-iris1211" }

# Forge
forge-kotlin1201 = { module = "thedarkcolour:kotlinforforge", version.ref = "kff1201" }
forge-kotlin1211 = { module = "thedarkcolour:kotlinforforge", version.ref = "kff1211" }
forge-mixinextras = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras" }
forge-kritter1201 = { module = "uwu.serenity.kritter:kritter-forge", version.ref = "kritter1201" }
forge-kritter1211 = { module = "uwu.serenity.kritter:kritter-forge", version.ref = "kritter1211" }
forge-iris1201 = { module = "maven.modrinth:oculus", version.ref = "forge-iris1201" }
forge-iris1211 = { module = "maven.modrinth:iris", version.ref = "forge-iris1211" }

[bundles]

[plugins]
cloche = { id = "earth.terrarium.cloche", version.ref = "cloche" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }